export const AUTH_SIGN_IN_WITH_GOOGLE_START = "AUTH/SIGN_IN_WITH_GOOGLE_START";
export const AUTH_SIGN_IN_PENDING = "AUTH/SIGN_IN_PENDING";
export const AUTH_SIGN_IN_ERROR = "AUTH/SIGN_IN_ERROR";
export const AUTH_SIGN_IN_DONE = "AUTH/SIGN_IN_DONE";
export const AUTH_SIGN_OUT_DONE = "AUTH/SIGN_OUT_DONE";
export const AUTH_SIGN_OUT_START = "AUTH/SIGN_OUT_START";
export const AUTH_SIGN_OUT_ERROR = "AUTH/SIGN_OUT_ERROR";

export const ACCOUNTS_WATCH_START = "ACCOUNTS/WATCH_START";
export const ACCOUNTS_WATCH_STOP = "ACCOUNTS/WATCH_STOP";
export const ACCOUNTS_WATCH_UPDATE = "ACCOUNTS/WATCH_UPDATE";
export const ACCOUNTS_WATCH_ERROR = "ACCOUNTS/WATCH_ERROR";

export const ACCOUNTS_ADD_START = "ACCOUNTS/ADD_START";
export const ACCOUNTS_ADD_DONE = "ACCOUNTS/ADD_DONE";
export const ACCOUNTS_ADD_ERROR = "ACCOUNTS/ADD_ERROR";
export const ACCOUNTS_UPDATE_START = "ACCOUNTS/UPDATE_START";
export const ACCOUNTS_UPDATE_DONE = "ACCOUNTS/UPDATE_DONE";
export const ACCOUNTS_UPDATE_ERROR = "ACCOUNTS/UPDATE_ERROR";
export const ACCOUNTS_FETCH_START = "ACCOUNTS/FETCH_START";
export const ACCOUNTS_FETCH_DONE = "ACCOUNTS/FETCH_DONE";
export const ACCOUNTS_FETCH_ERROR = "ACCOUNTS/FETCH_ERROR";

export const ACCOUNT_FETCH_START = "ACCOUNT/FETCH_START";
export const ACCOUNT_FETCH_PENDING = "ACCOUNT/FETCH_PENDING";
export const ACCOUNT_FETCH_DONE = "ACCOUNT/FETCH_DONE";
export const ACCOUNT_FETCH_ERROR = "ACCOUNT/FETCH_ERROR";

export const CURRENCIES_FETCH_START = "CURRENCIES/FETCH_START";
export const CURRENCIES_FETCH_DONE = "CURRENCIES/FETCH_DONE";
export const CURRENCIES_FETCH_PENDING = "CURRENCIES/FETCH_PENDING";
export const CURRENCIES_FETCH_ERROR = "CURRENCIES/FETCH_ERROR";

export const STATUSES_FETCH_START = "STATUSES/FETCH_START";
export const STATUSES_FETCH_DONE = "STATUSES/FETCH_DONE";
export const STATUSES_FETCH_PENDING = "STATUSES/FETCH_PENDING";
export const STATUSES_FETCH_ERROR = "STATUSES/FETCH_ERROR";

export const MODAL_OPEN = "MODAL/OPEN";
export const MODAL_CLOSE = "MODAL/CLOSE";
