export const AUTH_SIGN_IN_WITH_GOOGLE_ASYNC = "AUTH/SIGN_IN_WITH_GOOGLE_ASYNC";
export const AUTH_SIGN_IN_WITH_GOOGLE_SUCCESS =
  "AUTH/SIGN_IN_WITH_GOOGLE_SUCCESS";
export const AUTH_SIGN_IN_WITH_GOOGLE_ERROR = "AUTH/SIGN_IN_WITH_GOOGLE_ERROR";
export const AUTH_SIGN_OUT = "AUTH/SIGN_OUT";
