export const AUTH_SIGN_IN_WITH_GOOGLE_START = "AUTH/SIGN_IN_WITH_GOOGLE_START";
export const AUTH_SIGN_IN_PENDING = "AUTH/SIGN_IN_PENDING";
export const AUTH_SIGN_IN_ERROR = "AUTH/SIGN_IN_ERROR";
export const AUTH_SIGN_IN_DONE = "AUTH/SIGN_IN_DONE";
export const AUTH_SIGN_OUT_DONE = "AUTH/SIGN_OUT_DONE";
export const AUTH_SIGN_OUT_START = "AUTH/SIGN_OUT_START";
export const AUTH_SIGN_OUT_ERROR = "AUTH/SIGN_OUT_ERROR";
